ALTER TABLE issues ADD COLUMN IF NOT EXISTS ai_summary TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS ai_suggestions JSONB DEFAULT '[]';
ALTER TABLE issues ADD COLUMN IF NOT EXISTS ai_generated_at TIMESTAMPTZ;
